package com.estes.myestes.BillOfLading.web.dao.sql;

import static com.estes.myestes.BillOfLading.web.dao.sql.Schema.DATALIB;

public interface BolQuery {
	
	public static final String BOL_HEADER_TABLE         = "EBG10P100";
	
	public static final String BOL_HEADER_STAGING_TABLE = "EBG10P200";
	
	public static final String BOL_SHIPPING_LABEL_TABLE = "EBG10P101";
	
	public static final String BOL_EMAIL_AND_FAX_NOTIFICATION_TABLE="EBG10P102";
	
	public static final String BOL_REFERENCE_TABLE      = "EBG10P103";
	
	
	public static final String BOL_COMMODITY_TABLE      = "EBG10P104";
	
	public static final String BOL_ACCESSORIAL_TABLE    = "EBG10P108";
	
	
	
	/**
	 *  This query is for BOL listing, pagination, sorting and filtering.
	 */
	public static final String GET_BOL_LIST= 
			  " SELECT * FROM ( "
				+ "	SELECT T1.BOL_SEQ AS BOL_SEQUENCE,"
				+ " T1.BOL_NUM as BOL_NUMBER,"
				+ " T1.BOL_DATE ,"
				+ " DIGITS(T1.PRO_OT) AS PRO_OT, "
				+ " DIGITS(T1.PRO_NUM) AS PRO_NUM,"
				+ " CONCAT(CONCAT(DIGITS(T1.PRO_OT),'-'),DIGITS(T1.PRO_NUM)) AS PRO_NUMBER,"
				+ " T1.SHIP_COMPANY AS SHIPPER_COMPANY_NAME,"
				+ " T1.SHIP_FIRST_NAME AS SHIPPER_FIRST_NAME,"
				+ " T1.SHIP_LAST_NAME AS SHIPPER_LAST_NAME,"
				+ " T1.CONS_COMPANY_NAME AS CONSIGNEE_COMPANY_NAME,"
				+ " T1.CONS_FIRST_NAME AS CONSIGNEE_FIRST_NAME,"
				+ " T1.CONS_LAST_NAME AS CONSIGNEE_LAST_NAME,"
				+ " T2.STR_LAB AS SHIPPING_LABEL_START,"
				+ " T2.TOT_LAB AS SHIPPING_LABEL_TOTAL,"
				+ " T2.LABEL_TYPE AS SHIPPING_LABEL_TYPE,"
				+ " CASE WHEN INT(REGEXP_REPLACE(T2.LABEL_TYPE,'\\D','0'))>0 THEN 1 ELSE 0 END AS HAS_SHIPPING_LABEL,"
				+ " T1.USER_NAME as USERNAME "
				+ " FROM "+DATALIB+"."+BOL_HEADER_TABLE+" AS T1"
				+ " LEFT OUTER JOIN "+DATALIB+"."+BOL_SHIPPING_LABEL_TABLE+" AS T2"
				+ " ON CHAR(T1.BOL_SEQ) = T2.BOL_SEQ"
				+ " WHERE T1.COMPLETE = 'Y'"
			+ ") WHERE USERNAME = ?";
	
	public static final String COUNT_BOL="SELECT COUNT(*) FROM "+DATALIB+"."+BOL_HEADER_TABLE + " AS T1 WHERE T1.USER_NAME = ? AND T1.BOL_SEQUENCE = ?";
	
	public static final String GET_BOL_HEADER="SELECT "
			+ " T1.*,"
			+ " DIGITS(T1.PRO_ORIG_TERM) AS PR_OT,"
			+ " DIGITS(T1.PRO_NUMBER) AS PR_NM,"
			+ " T2.START_LABEL,"
			+ " T2.TOTAL_LABEL,"
			+ " T2.LABEL_TYPE,"
			+ " T3.EMAIL_LABELS_SHIPPER, "
			+ " T3.EMAIL_LABELS_CONSIGNEE, "
			+ " T3.EMAIL_LABELS_THIRDPARTY, "
			+ " T3.EMAIL_LABELS_OTHER, "
			+ " T3.EMAIL_LABELS_OTHER_ADDRESS, "
			+ " T3.FAX_BOL_SHIPPER, "
			+ " T3.FAX_BOL_CONSIGNEE, "
			+ " T3.FAX_BOL_THIRDPARTY, "
			+ " T3.FAX_BOL_OTHER, "
			+ " T3.FAX_BOL_NUMBER, "
			+ " T3.EMAIL_TRACKING_OTHER "
			+ " FROM "+DATALIB+"."+BOL_HEADER_TABLE + " AS T1"
			+ " LEFT JOIN "+DATALIB+"."+BOL_SHIPPING_LABEL_TABLE +" AS T2"
			+ " ON T1.BOL_SEQUENCE = T2.BOL_SEQUENCE"
			+ " LEFT  JOIN "+DATALIB+"."+BOL_EMAIL_AND_FAX_NOTIFICATION_TABLE+ " AS T3 "
			+ " ON T1.BOL_SEQUENCE=T3.BOL_SEQUENCE "
			+ " WHERE T1.USER_NAME = ? AND T1.BOL_SEQUENCE = ?";
	
	
	public static final String GET_BOL_COMMODITY = "SELECT "
			+ " SHIP_INFO_SEQUENCE AS COMMODITY_ID,"
			+ " HAZ_MAT AS HAZMAT,"
			+ " GOODS_QUANTITY AS GOODS_UNIT,"
			+ " GOODS_TYPE AS GOODS_TYPE,"
			+ " WEIGHT AS GOODS_WEIGHT,"
			+ " CLASS AS SHIPMENT_CLASS,"
			+ " NMFC AS NMFC,"
			+ " NMFC_SUB AS NMFC_EXT,"
			+ " SHIP_UNIT_QUANT AS NUMBER_OF_PACKAGE,"
			+ " SHIP_UNIT_TYPE AS PACKAGE_TYPE,"
			+ " DESCRIPTION AS DESCRIPTION,"
			+ " DIM_HEIGHT AS HEIGHT,"
			+ " DIM_LENGTH AS WEIGHT,"
			+ " DIM_WIDTH AS LENGTH"
			+ " FROM "+DATALIB+"."+BOL_COMMODITY_TABLE
			+ " WHERE BOL_SEQUENCE = ?";
	
	public static final String GET_BOL_REFERENCE   = "SELECT "
			+ " REFERENCE_NO_SEQUENCE AS  REFERENCE_ID,"
			+ " REF_NO AS  REFERENCE_NUMBER,"
			+ " TYPE AS  REFERENCE_TYPE,"
			+ " CARTONS AS  CARTOON,"
			+ " WEIGHT AS  WEIGHT"
			+ " FROM "+DATALIB+"."+BOL_REFERENCE_TABLE
			+ " WHERE BOL_SEQUENCE = ?";
	
	
	public static final String GET_BOL_ACCESSORIAL  = "SELECT "
			+ " ACCESSORIAL_CODE AS CODE, "
			+ " '' AS DESCRIPTION "
			+ " FROM "+DATALIB+"."+BOL_ACCESSORIAL_TABLE
			+ " WHERE BOL_SEQUENCE = ?";
	
	public static final String SET_SERVICE_LEVEL_IN_STAGING = "UPDATE "+DATALIB+"."+BOL_HEADER_STAGING_TABLE+" SET GOLD_STAR=? where USER_NAME=? AND BOL_SEQUENCE=?";

}
