package com.estes.myestes.BillOfLading.web.dao.sql;

public interface PickupRequestValidationQuery {
	
	public static final  String VALID_PICKUP_DATE_QUERY="SELECT  WDDAT8, WDDAY, WDEXCP  FROM "+Schema.DATALIB+".FRP932 "
			+ " WHERE WDDAT8  = ? "
			+ " AND WDDAT8 >= (SELECT INT(VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMMDD'))"
			+ " FROM SYSIBM.SYSDUMMY1)"
			+ " AND WDDAT8 <= (SELECT INT(VARCHAR_FORMAT(CURRENT TIMESTAMP + 30 DAY, 'YYYYMMDD'))"
			+ " FROM SYSIBM.SYSDUMMY1) ";
	/**
	 * 
	 */
	public static final  String QUERY_ACCOUNT_BELONGS_91    = "SELECT count(*) FROM FBFILES.RAP001 WHERE  CMOCC = ? AND CMCUST = ? ";
	public static final  String QUERY_WEB_GROUP_ACCOUNT     = "SELECT count(*) FROM ESTESRTGY2.QNP245 WHERE  QAGRPC = ? AND QACUSC = ? ";
	public static final  String QUERY_ACCOUNT_BELONGS_NATIONAL_ACCOUNT = "SELECT count(*) FROM FBFILES.RAP001 WHERE CMNA = ? AND CMCUST = ?  ";
	
	
	public static final  String QUERY_ACTIVE_ACCOUNT = "SELECT COUNT(*) FROM FBFILES.RAP001 WHERE CMCUST = ? AND CMSTAT = 'A'";
	
	public static final String QUERY_SHIPPER_INFO_BY_ACCOUNT_CODE = "SELECT CMNAME AS COMPANY, CMCONT,CMADR1 AS ADDRESS1, CMADR2 AS ADDRESS2, CMCITY AS CITY, CMST AS STATE, CMZIP AS ZIP FROM FBFILES.RAP001 WHERE CMCUST=?";
	
}
