//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated for use by Estes Express Lines Inc.
//


package com.estes.dto.ecm.image.print.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.estes.dto.ecm.image.common.Created;
import com.estes.dto.ecm.image.common.ImageDetails;
import com.estes.dto.ecm.image.common.ImageStatus;
import com.estes.dto.ecm.image.common.Metadata;
import com.estes.dto.ecm.image.common.Option;
import com.estes.dto.ecm.image.common.QueryRequest;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.estes.dto.ecm.image.print.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImagePrintRequest_QNAME = new QName("http://www.estes-express.com/ECM/imaging/queryImage", "ImagePrintRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.estes.dto.ecm.image.print.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrintRequest }
     * 
     */
    public PrintRequest createPrintRequest() {
        return new PrintRequest();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link ImageDetails }
     * 
     */
    public ImageDetails createImageDetails() {
        return new ImageDetails();
    }

    /**
     * Create an instance of {@link Created }
     * 
     */
    public Created createCreated() {
        return new Created();
    }

    /**
     * Create an instance of {@link ImageStatus }
     * 
     */
    public ImageStatus createImageStatus() {
        return new ImageStatus();
    }

    /**
     * Create an instance of {@link QueryRequest }
     * 
     */
    public QueryRequest createQueryRequest() {
        return new QueryRequest();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.estes-express.com/ECM/imaging/queryImage", name = "ImagePrintRequest")
    public JAXBElement<PrintRequest> createImagePrintRequest(PrintRequest value) {
        return new JAXBElement<PrintRequest>(_ImagePrintRequest_QNAME, PrintRequest.class, null, value);
    }

}
