package com.estes.myestes.BillOfLading.web.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.estes.myestes.BillOfLading.util.EstesUtil;
import com.estes.myestes.BillOfLading.web.dto.DraftHead;

public class DraftHeadMapper implements  RowMapper<DraftHead>{

	@Override
	public DraftHead mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		DraftHead draft = new DraftHead();
		
		String userName = rs.getString("USER_NAME").trim();
		String calledByPgm = rs.getString("CALLED_BY_PGM").trim();
		String bolDate = rs.getString("BOL_DATE").trim();
		String pickUp = rs.getString("PICK_UP").trim();
		String pickUpDate = rs.getString("PICK_UP_DATE").trim();
		String bolNumber = rs.getString("BOL_NUMBER").trim();
		String proOrigTerm = rs.getString("PRO_ORIG_TERM").trim();
		String proNumber = rs.getString("PRO_NUMBER").trim();
		String autoAsignPro = rs.getString("AUTO_ASIGN_PRO").trim();
		String pickupReqUser = rs.getString("PICKUP_REQ_USER").trim();
		String userFirstName = rs.getString("USER_FIRST_NAME").trim();
		String userLastName = rs.getString("USER_LAST_NAME").trim();
		String userAreaCode = rs.getString("USER_AREA_CODE").trim();
		String userExchange = rs.getString("USER_EXCHANGE").trim();
		String userLast4 = rs.getString("USER_LAST_4").trim();
		String userExt = rs.getString("USER_EXT").trim();
		String userEmail = rs.getString("USER_EMAIL").trim();
		String shipCompany = rs.getString("SHIP_COMPANY").trim();
		String shipAccount = rs.getString("SHIP_ACCOUNT").trim();
		String shipFirstName = rs.getString("SHIP_FIRST_NAME").trim();
		String shipLastName = rs.getString("SHIP_LAST_NAME").trim();
		String shipLocation = rs.getString("SHIP_LOCATION").trim();
		String shipAreaCode = rs.getString("SHIP_AREA_CODE").trim();
		String shipExchange = rs.getString("SHIP_EXCHANGE").trim();
		String shipLast4 = rs.getString("SHIP_LAST_4").trim();
		String shipExt = rs.getString("SHIP_EXT").trim();
		String shipFaxAreaCode = rs.getString("SHIP_FAX_AREA_CODE").trim();
		String shipFaxExchange = rs.getString("SHIP_FAX_EXCHANGE").trim();
		String shipFaxLast4 = rs.getString("SHIP_FAX_LAST_4").trim();
		String shipCountry = rs.getString("SHIP_COUNTRY").trim();
		String shipStr1Address = rs.getString("SHIP_STR1_ADDRESS").trim();
		String shipStr2Address = rs.getString("SHIP_STR2_ADDRESS").trim();
		String shipCity = rs.getString("SHIP_CITY").trim();
		String shipState = rs.getString("SHIP_STATE").trim();
		String shipZip = rs.getString("SHIP_ZIP").trim();
		String shipZip4 = rs.getString("SHIP_ZIP_4").trim();
		String consCompanyName = rs.getString("CONS_COMPANY_NAME").trim();
		String consAccount = rs.getString("CONS_ACCOUNT").trim();
		String consFirstName = rs.getString("CONS_FIRST_NAME").trim();
		String consLastName = rs.getString("CONS_LAST_NAME").trim();
		String consLocationNumber = rs.getString("CONS_LOCATION_NUMBER").trim();
		String consPnAreaCode = rs.getString("CONS_PN_AREA_CODE").trim();
		String consPnExchange = rs.getString("CONS_PN_EXCHANGE").trim();
		String consPnLast4 = rs.getString("CONS_PN_LAST_4").trim();
		String consPnExtension = rs.getString("CONS_PN_EXTENSION").trim();
		String consFnAreaCode = rs.getString("CONS_FN_AREA_CODE").trim();
		String consFnExchange = rs.getString("CONS_FN_EXCHANGE").trim();
		String consFnLast4 = rs.getString("CONS_FN_LAST_4").trim();
		String consCountry = rs.getString("CONS_COUNTRY").trim();
		String consStAddr1 = rs.getString("CONS_ST_ADDR_1").trim();
		String consStAddr2 = rs.getString("CONS_ST_ADDR_2").trim();
		String consCity = rs.getString("CONSCITY").trim();
		String consState = rs.getString("CONSSTATE").trim();
		String consZip = rs.getString("CONSZIP").trim();
		String consZip4 = rs.getString("CONS_ZIP_4").trim();
		String payorCode = rs.getString("PAYOR_CODE").trim();
		String termsCode = rs.getString("TERMS_CODE").trim();
		String tptyCompanyName = rs.getString("TPTY_COMPANY_NAME").trim();
		String tptyAccount = rs.getString("TPTY_ACCOUNT").trim();
		String tptyFirstName = rs.getString("TPTY_FIRST_NAME").trim();
		String tptyLastName = rs.getString("TPTY_LAST_NAME").trim();
		String tptyLocationNumber = rs.getString("TPTY_LOCATION_NUMBER").trim();
		String tptyPnAreaCode = rs.getString("TPTY_PN_AREA_CODE").trim();
		String tptyPnExchange = rs.getString("TPTY_PN_EXCHANGE").trim();
		String tptyPnLast4 = rs.getString("TPTY_PN_LAST_4").trim();
		String tptyPnExtension = rs.getString("TPTY_PN_EXTENSION").trim();
		String tptyFnAreaCode = rs.getString("TPTY_FN_AREA_CODE").trim();
		String tptyFnExchange = rs.getString("TPTY_FN_EXCHANGE").trim();
		String tptyFnLast4 = rs.getString("TPTY_FN_LAST_4").trim();
		String tptyCountry = rs.getString("TPTY_COUNTRY").trim();
		String tptyStAddr1 = rs.getString("TPTY_ST_ADDR_1").trim();
		String tptyStAddr2 = rs.getString("TPTY_ST_ADDR_2").trim();
		String tptycity = rs.getString("TPTYCITY").trim();
		String tptystate = rs.getString("TPTYSTATE").trim();
		String tptyzip = rs.getString("TPTYZIP").trim();
		String tptyZip4 = rs.getString("TPTY_ZIP_4").trim();
		String codFlg = rs.getString("COD_FLG").trim();
		String codAmount = rs.getString("COD_AMOUNT").trim();
		String codPaymentType = rs.getString("COD_PAYMENT_TYPE").trim();
		String codFeePaidby = rs.getString("COD_FEE_PAIDBY").trim();
		String codname = rs.getString("CODNAME").trim();
		String codFirstName = rs.getString("COD_FIRST_NAME").trim();
		String codLastName = rs.getString("COD_LAST_NAME").trim();
		String codLocationNumber = rs.getString("COD_LOCATION_NUMBER").trim();
		String codPnAreaCode = rs.getString("COD_PN_AREA_CODE").trim();
		String codPnExchange = rs.getString("COD_PN_EXCHANGE").trim();
		String codPnLast4 = rs.getString("COD_PN_LAST_4").trim();
		String codPnExtension = rs.getString("COD_PN_EXTENSION").trim();
		String codCountry = rs.getString("COD_COUNTRY").trim();
		String codStAddr1 = rs.getString("COD_ST_ADDR_1").trim();
		String codStAddr2 = rs.getString("COD_ST_ADDR_2").trim();
		String codCity = rs.getString("CODCITY").trim();
		String codState = rs.getString("CODSTATE").trim();
		String codZip = rs.getString("CODZIP").trim();
		String codZip4 = rs.getString("COD_ZIP_4").trim();
		String goldStar = rs.getString("GOLD_STAR").trim();
		String goldStarPickup = rs.getString("GOLD_STAR_PICKUP").trim();
		String goldStarQuote = rs.getString("GOLD_STAR_QUOTE").trim();
		String goldService = rs.getString("GOLD_SERVICE").trim();
		String volumeShipment = rs.getString("VOLUME_SHIPMENT").trim();
		String volumeQuote = rs.getString("VOLUME_QUOTE").trim();
		String shipperEmail = rs.getString("SHIPPER_EMAIL").trim();
		String consigneeEmail = rs.getString("CONSIGNEE_EMAIL").trim();
		String thirdpartyEmail = rs.getString("THIRDPARTY_EMAIL").trim();
		String codEmail = rs.getString("COD_EMAIL").trim();
		String emailBolShipper = rs.getString("EMAIL_BOL_SHIPPER").trim();
		String emailBolCons = rs.getString("EMAIL_BOL_CONS").trim();
		String emailBolTpty = rs.getString("EMAIL_BOL_TPTY").trim();
		String emailTrkShipper = rs.getString("EMAIL_TRK_SHIPPER").trim();
		String emailTrkCons = rs.getString("EMAIL_TRK_CONS").trim();
		String emailTrkTpty = rs.getString("EMAIL_TRK_TPTY").trim();
		String totalPackages = rs.getString("TOTAL_PACKAGES").trim();
		String totalShipUnits = rs.getString("TOTAL_SHIP_UNITS").trim();
		String totalWeight = rs.getString("TOTAL_WEIGHT").trim();
		String totalValue = rs.getString("TOTAL_VALUE").trim();
		String hazmatContact = rs.getString("HAZMAT_CONTACT").trim();
		String hazmatAreaCode = rs.getString("HAZMAT_AREA_CODE").trim();
		String hazmatExchange = rs.getString("HAZMAT_EXCHANGE").trim();
		String hazmatLast4 = rs.getString("HAZMAT_LAST_4").trim();
		String hazmatExtension = rs.getString("HAZMAT_EXTENSION").trim();
		String pickupInstructions = rs.getString("PICKUP_INSTRUCTIONS").trim();
		String specialInstructions = rs.getString("SPECIAL_INSTRUCTIONS").trim();
		String cube = rs.getString("CUBE").trim();
		String availableTime = rs.getString("AVAILABLE_TIME").trim();
		String availableAmPm = rs.getString("AVAILABLE_AM_PM").trim();
		String closeTime = rs.getString("CLOSE_TIME").trim();
		String closeAmPm = rs.getString("CLOSE_AM_PM").trim();
		String startLabel = rs.getString("START_LABEL").trim();
		String totalLabel = rs.getString("TOTAL_LABEL").trim();
		String faxToShipper = rs.getString("FAX_TO_SHIPPER").trim();
		String faxToConsignee = rs.getString("FAX_TO_CONSIGNEE").trim();
		String faxToThirdParty = rs.getString("FAX_TO_THIRD_PARTY").trim();
		String trailerNumber = rs.getString("TRAILER_NUMBER").trim();
		String sealNumber = rs.getString("SEAL_NUMBER").trim();
		String sCAC = rs.getString("S_C_A_C").trim();
		String masterBol = rs.getString("MASTER_BOL").trim();
		String masterBolNum = rs.getString("MASTER_BOL_NUM").trim();
		String bolType = rs.getString("BOL_TYPE").trim();
		String pickupDetails = rs.getString("PICKUP_DETAILS").trim();
		String shipmentDetails = rs.getString("SHIPMENT_DETAILS").trim();
		String notifyPickupReceipt = rs.getString("NOTIFY_PICKUP_RECEIPT").trim();
		String notifyPickupAccept = rs.getString("NOTIFY_PICKUP_ACCEPT").trim();
		String notifyPickupReject = rs.getString("NOTIFY_PICKUP_REJECT").trim();
		String notifyPickupBegin = rs.getString("NOTIFY_PICKUP_BEGIN").trim();
		String notifyPickupComplete = rs.getString("NOTIFY_PICKUP_COMPLETE").trim();
		String emailBolOther = rs.getString("EMAIL_BOL_OTHER").trim();
		String emailTrkOther = rs.getString("EMAIL_TRK_OTHER").trim();
		String emailLabelShipper = rs.getString("EMAIL_LABEL_SHIPPER").trim();
		String emailLabelCons = rs.getString("EMAIL_LABEL_CONS").trim();
		String emailLabelTpty = rs.getString("EMAIL_LABEL_TPTY").trim();
		String emailLabelOther = rs.getString("EMAIL_LABEL_OTHER").trim();
		String faxToOther = rs.getString("FAX_TO_OTHER").trim();
		String otherFaxAreaCode = rs.getString("OTHER_FAX_AREA_CODE").trim();
		String otherFaxExchange = rs.getString("OTHER_FAX_EXCHANGE").trim();
		String otherFaxLast4 = rs.getString("OTHER_FAX_LAST_4").trim();
		String labelType = rs.getString("LABEL_TYPE").trim();
		String emailOtherAddr = rs.getString("EMAIL_OTHER_ADDR").trim();
		String faxBolShipper = rs.getString("FAX_BOL_SHIPPER").trim();
		String faxBolConsignee = rs.getString("FAX_BOL_CONSIGNEE").trim();
		String faxBolTpty = rs.getString("FAX_BOL_TPTY").trim();
		String faxBolOther = rs.getString("FAX_BOL_OTHER").trim();
		String faxBolNumber = rs.getString("FAX_BOL_NUMBER").trim();

		
		
		
		
		draft.setUserName(userName);
		draft.setCalledByPgm(calledByPgm);
		draft.setBolDate(EstesUtil.formatDate(EstesUtil.removeNonDigit(bolDate),"yyyyMMdd"));
		draft.setPickUp(pickUp);
		draft.setPickUpDate(pickUpDate);
		draft.setBolNumber(bolNumber);
		draft.setProOrigTerm(proOrigTerm);
		draft.setProNumber(proNumber);
		draft.setAutoAsignPro(autoAsignPro);
		draft.setPickupReqUser(pickupReqUser);
		draft.setUserFirstName(userFirstName);
		draft.setUserLastName(userLastName);
		draft.setUserAreaCode(userAreaCode);
		draft.setUserExchange(userExchange);
		draft.setUserLast4(userLast4);
		draft.setUserExt(userExt);
		draft.setUserEmail(userEmail);
		draft.setShipCompany(shipCompany);
		draft.setShipAccount(shipAccount);
		draft.setShipFirstName(shipFirstName);
		draft.setShipLastName(shipLastName);
		draft.setShipLocation(shipLocation);
		draft.setShipAreaCode(shipAreaCode);
		draft.setShipExchange(shipExchange);
		draft.setShipLast4(shipLast4);
		draft.setShipExt(shipExt);
		draft.setShipFaxAreaCode(shipFaxAreaCode);
		draft.setShipFaxExchange(shipFaxExchange);
		draft.setShipFaxLast4(shipFaxLast4);
		draft.setShipCountry(shipCountry);
		draft.setShipStr1Address(shipStr1Address);
		draft.setShipStr2Address(shipStr2Address);
		draft.setShipCity(shipCity);
		draft.setShipState(shipState);
		draft.setShipZip(shipZip);
		draft.setShipZip4(shipZip4);
		draft.setConsCompanyName(consCompanyName);
		draft.setConsAccount(consAccount);
		draft.setConsFirstName(consFirstName);
		draft.setConsLastName(consLastName);
		draft.setConsLocationNumber(consLocationNumber);
		draft.setConsPnAreaCode(consPnAreaCode);
		draft.setConsPnExchange(consPnExchange);
		draft.setConsPnLast4(consPnLast4);
		draft.setConsPnExtension(consPnExtension);
		draft.setConsFnAreaCode(consFnAreaCode);
		draft.setConsFnExchange(consFnExchange);
		draft.setConsFnLast4(consFnLast4);
		draft.setConsCountry(consCountry);
		draft.setConsStAddr1(consStAddr1);
		draft.setConsStAddr2(consStAddr2);
		draft.setConsCity(consCity);
		draft.setConsState(consState);
		draft.setConsZip(consZip);
		draft.setConsZip4(consZip4);
		draft.setPayorCode(payorCode);
		draft.setTermsCode(termsCode);
		draft.setTptyCompanyName(tptyCompanyName);
		draft.setTptyAccount(tptyAccount);
		draft.setTptyFirstName(tptyFirstName);
		draft.setTptyLastName(tptyLastName);
		draft.setTptyLocationNumber(tptyLocationNumber);
		draft.setTptyPnAreaCode(tptyPnAreaCode);
		draft.setTptyPnExchange(tptyPnExchange);
		draft.setTptyPnLast4(tptyPnLast4);
		draft.setTptyPnExtension(tptyPnExtension);
		draft.setTptyFnAreaCode(tptyFnAreaCode);
		draft.setTptyFnExchange(tptyFnExchange);
		draft.setTptyFnLast4(tptyFnLast4);
		draft.setTptyCountry(tptyCountry);
		draft.setTptyStAddr1(tptyStAddr1);
		draft.setTptyStAddr2(tptyStAddr2);
		draft.setTptyCity(tptycity);
		draft.setTptyState(tptystate);
		draft.setTptyZip(tptyzip);
		draft.setTptyZip4(tptyZip4);
		draft.setCodFlg(codFlg);
		draft.setCodAmount(codAmount);
		draft.setCodPaymentType(codPaymentType);
		draft.setCodFeePaidby(codFeePaidby);
		draft.setCodname(codname);
		draft.setCodFirstName(codFirstName);
		draft.setCodLastName(codLastName);
		draft.setCodLocationNumber(codLocationNumber);
		draft.setCodPnAreaCode(codPnAreaCode);
		draft.setCodPnExchange(codPnExchange);
		draft.setCodPnLast4(codPnLast4);
		draft.setCodPnExtension(codPnExtension);
		draft.setCodCountry(codCountry);
		draft.setCodStAddr1(codStAddr1);
		draft.setCodStAddr2(codStAddr2);
		draft.setCodCity(codCity);
		draft.setCodState(codState);
		draft.setCodZip(codZip);
		draft.setCodZip4(codZip4);
		draft.setGoldStar(goldStar);
		draft.setGoldStarPickup(goldStarPickup);
		draft.setGoldStarQuote(goldStarQuote);
		draft.setGoldService(goldService);
		draft.setVolumeShipment(volumeShipment);
		draft.setVolumeQuote(volumeQuote);
		draft.setShipperEmail(shipperEmail);
		draft.setConsigneeEmail(consigneeEmail);
		draft.setThirdpartyEmail(thirdpartyEmail);
		draft.setCodEmail(codEmail);
		draft.setEmailBolShipper(emailBolShipper);
		draft.setEmailBolCons(emailBolCons);
		draft.setEmailBolTpty(emailBolTpty);
		draft.setEmailTrkShipper(emailTrkShipper);
		draft.setEmailTrkCons(emailTrkCons);
		draft.setEmailTrkTpty(emailTrkTpty);
		draft.setTotalPackages(totalPackages);
		draft.setTotalShipUnits(totalShipUnits);
		draft.setTotalWeight(totalWeight);
		draft.setTotalValue(totalValue);
		draft.setHazmatContact(hazmatContact);
		draft.setHazmatAreaCode(hazmatAreaCode);
		draft.setHazmatExchange(hazmatExchange);
		draft.setHazmatLast4(hazmatLast4);
		draft.setHazmatExtension(hazmatExtension);
		draft.setPickupInstructions(pickupInstructions);
		draft.setSpecialInstructions(specialInstructions);
		draft.setCube(cube);
		draft.setAvailableTime(availableTime);
		draft.setAvailableAmPm(availableAmPm);
		draft.setCloseTime(closeTime);
		draft.setCloseAmPm(closeAmPm);
		draft.setStartLabel(startLabel);
		draft.setTotalLabel(totalLabel);
		draft.setFaxToShipper(faxToShipper);
		draft.setFaxToConsignee(faxToConsignee);
		draft.setFaxToThirdParty(faxToThirdParty);
		draft.setTrailerNumber(trailerNumber);
		draft.setSealNumber(sealNumber);
		draft.setScac(sCAC);
		draft.setMasterBol(masterBol);
		draft.setMasterBolNum(masterBolNum);
		draft.setBolType(bolType);
		draft.setPickupDetails(pickupDetails);
		draft.setShipmentDetails(shipmentDetails);
		draft.setNotifyPickupReceipt(notifyPickupReceipt);
		draft.setNotifyPickupAccept(notifyPickupAccept);
		draft.setNotifyPickupReject(notifyPickupReject);
		draft.setNotifyPickupBegin(notifyPickupBegin);
		draft.setNotifyPickupComplete(notifyPickupComplete);
		draft.setEmailBolOther(emailBolOther);
		draft.setEmailTrkOther(emailTrkOther);
		draft.setEmailLabelShipper(emailLabelShipper);
		draft.setEmailLabelCons(emailLabelCons);
		draft.setEmailLabelTpty(emailLabelTpty);
		draft.setEmailLabelOther(emailLabelOther);
		draft.setFaxToOther(faxToOther);
		draft.setOtherFaxAreaCode(otherFaxAreaCode);
		draft.setOtherFaxExchange(otherFaxExchange);
		draft.setOtherFaxLast4(otherFaxLast4);
		draft.setLabelType(labelType);
		draft.setEmailOtherAddr(emailOtherAddr);
		draft.setFaxBolShipper(faxBolShipper);
		draft.setFaxBolConsignee(faxBolConsignee);
		draft.setFaxBolTpty(faxBolTpty);
		draft.setFaxBolOther(faxBolOther);
		draft.setFaxBolNumber(faxBolNumber);
		return draft;
	}

}
