//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated for use by Estes Express Lines Inc.
//


package com.estes.dto.ecm.image.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docTypes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *         &lt;element name="queryOptions" type="{}option" minOccurs="0"/>
 *         &lt;element name="terminalNumbers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *         &lt;element name="scanStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="verificationUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="created" type="{}created" minOccurs="0"/>
 *         &lt;element name="metadata" type="{}metadata" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metadataLogicalOperator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="imageStatus" type="{}imageStatus" minOccurs="0"/>
 *         &lt;element name="logicalOperator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="generateSecureURLFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryRequest", propOrder = {
    "docTypes",
    "queryOptions",
    "terminalNumbers",
    "scanStation",
    "verificationUser",
    "created",
    "metadata",
    "metadataLogicalOperator",
    "imageStatus",
    "logicalOperator",
    "generateSecureURLFlag"
})
public class QueryRequest {

    protected List<String> docTypes;
    protected Option queryOptions;
    protected List<String> terminalNumbers;
    protected String scanStation;
    protected String verificationUser;
    protected Created created;
    protected List<Metadata> metadata;
    @XmlElement(nillable = true)
    protected String metadataLogicalOperator;
    protected ImageStatus imageStatus;
    @XmlElement(nillable = true)
    protected String logicalOperator;
    @XmlElement(nillable = true)
    protected Boolean generateSecureURLFlag;

    /**
     * Gets the value of the docTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDocTypes() {
        if (docTypes == null) {
            docTypes = new ArrayList<String>();
        }
        return this.docTypes;
    }

    /**
     * Gets the value of the queryOptions property.
     * 
     * @return
     *     possible object is
     *     {@link Option }
     *     
     */
    public Option getQueryOptions() {
        return queryOptions;
    }

    /**
     * Sets the value of the queryOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Option }
     *     
     */
    public void setQueryOptions(Option value) {
        this.queryOptions = value;
    }

    /**
     * Gets the value of the terminalNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminalNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminalNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTerminalNumbers() {
        if (terminalNumbers == null) {
            terminalNumbers = new ArrayList<String>();
        }
        return this.terminalNumbers;
    }

    /**
     * Gets the value of the scanStation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScanStation() {
        return scanStation;
    }

    /**
     * Sets the value of the scanStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScanStation(String value) {
        this.scanStation = value;
    }

    /**
     * Gets the value of the verificationUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerificationUser() {
        return verificationUser;
    }

    /**
     * Sets the value of the verificationUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerificationUser(String value) {
        this.verificationUser = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link Created }
     *     
     */
    public Created getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link Created }
     *     
     */
    public void setCreated(Created value) {
        this.created = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Metadata }
     * 
     * 
     */
    public List<Metadata> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<Metadata>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the metadataLogicalOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataLogicalOperator() {
        return metadataLogicalOperator;
    }

    /**
     * Sets the value of the metadataLogicalOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataLogicalOperator(String value) {
        this.metadataLogicalOperator = value;
    }

    /**
     * Gets the value of the imageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ImageStatus }
     *     
     */
    public ImageStatus getImageStatus() {
        return imageStatus;
    }

    /**
     * Sets the value of the imageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageStatus }
     *     
     */
    public void setImageStatus(ImageStatus value) {
        this.imageStatus = value;
    }

    /**
     * Gets the value of the logicalOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalOperator() {
        return logicalOperator;
    }

    /**
     * Sets the value of the logicalOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalOperator(String value) {
        this.logicalOperator = value;
    }

    /**
     * Gets the value of the generateSecureURLFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGenerateSecureURLFlag() {
        return generateSecureURLFlag;
    }

    /**
     * Sets the value of the generateSecureURLFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGenerateSecureURLFlag(Boolean value) {
        this.generateSecureURLFlag = value;
    }

}
