//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 03:10:25 PM EDT 
//


package com.estes.ssdr.rest.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.estes.ssdr.rest.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentResponse_QNAME = new QName("", "documentResponse");
    private final static QName _DocumentRequest_QNAME = new QName("", "documentRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.estes.ssdr.rest.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentResponse }
     * 
     */
    public DocumentResponse createDocumentResponse() {
        return new DocumentResponse();
    }

    /**
     * Create an instance of {@link DocumentRequest }
     * 
     */
    public DocumentRequest createDocumentRequest() {
        return new DocumentRequest();
    }

    /**
     * Create an instance of {@link FaxNumber }
     * 
     */
    public FaxNumber createFaxNumber() {
        return new FaxNumber();
    }

    /**
     * Create an instance of {@link DocumentCodes }
     * 
     */
    public DocumentCodes createDocumentCodes() {
        return new DocumentCodes();
    }

    /**
     * Create an instance of {@link FaxInfo }
     * 
     */
    public FaxInfo createFaxInfo() {
        return new FaxInfo();
    }

    /**
     * Create an instance of {@link Emails }
     * 
     */
    public Emails createEmails() {
        return new Emails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "documentResponse")
    public JAXBElement<DocumentResponse> createDocumentResponse(DocumentResponse value) {
        return new JAXBElement<DocumentResponse>(_DocumentResponse_QNAME, DocumentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "documentRequest")
    public JAXBElement<DocumentRequest> createDocumentRequest(DocumentRequest value) {
        return new JAXBElement<DocumentRequest>(_DocumentRequest_QNAME, DocumentRequest.class, null, value);
    }

}
