//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated for use by Estes Express Lines Inc.
//


package com.estes.dto.ecm.image.delivery.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.estes.dto.ecm.image.common.ImageMetadata;
import com.estes.dto.ecm.image.common.QueriedImage;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.estes.dto.ecm.image.delivery.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImageDeliveryResponse_QNAME = new QName("http://www.estes-express.com/ECM/imaging/queryImage", "ImageDeliveryResponse");
    private final static QName _ImageQueryResponse_QNAME = new QName("http://www.estes-express.com/ECM/imaging/queryImage", "ImageQueryResponse");
    private final static QName _Image_QNAME = new QName("http://www.estes-express.com/ECM/imaging/queryImage", "image");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.estes.dto.ecm.image.delivery.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueriedImage }
     * 
     */
    public QueriedImage createQueriedImage() {
        return new QueriedImage();
    }

    /**
     * Create an instance of {@link DeliveryResponse }
     * 
     */
    public DeliveryResponse createDeliveryResponse() {
        return new DeliveryResponse();
    }

    /**
     * Create an instance of {@link QueryResponse }
     * 
     */
    public QueryResponse createQueryResponse() {
        return new QueryResponse();
    }

    /**
     * Create an instance of {@link ImageMetadata }
     * 
     */
    public ImageMetadata createImageMetadata() {
        return new ImageMetadata();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.estes-express.com/ECM/imaging/queryImage", name = "ImageDeliveryResponse")
    public JAXBElement<DeliveryResponse> createImageDeliveryResponse(DeliveryResponse value) {
        return new JAXBElement<DeliveryResponse>(_ImageDeliveryResponse_QNAME, DeliveryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.estes-express.com/ECM/imaging/queryImage", name = "ImageQueryResponse")
    public JAXBElement<QueryResponse> createImageQueryResponse(QueryResponse value) {
        return new JAXBElement<QueryResponse>(_ImageQueryResponse_QNAME, QueryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueriedImage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.estes-express.com/ECM/imaging/queryImage", name = "image")
    public JAXBElement<QueriedImage> createImage(QueriedImage value) {
        return new JAXBElement<QueriedImage>(_Image_QNAME, QueriedImage.class, null, value);
    }

}
