export const goodsTypes = [
  { value: 'BG', text: 'BAGS' },
  { value: 'BL', text: 'BALES' },
  { value: 'BR', text: 'BARRELS' },
  { value: 'BX', text: 'BOXES' },
  { value: 'BK', text: 'BUCKETS' },
  { value: 'BD', text: 'BUNDLES' },
  { value: 'CN', text: 'CANS' },
  { value: 'CT', text: 'CARTONS' },
  { value: 'CS', text: 'CASES' },
  { value: 'CR', text: 'CRATES' },
  { value: 'CY', text: 'CYLINDERS' },
  { value: 'DR', text: 'DRUMS' },
  { value: 'JC', text: 'JERRICAN' },
  { value: 'KT', text: 'KITS' },
  { value: 'PK', text: 'PACKAGES' },
  { value: 'PL', text: 'PAILS' },
  { value: 'PT', text: 'PALLETS' },
  { value: 'RE', text: 'REELS' },
  { value: 'RL', text: 'ROLLS' },
  { value: 'SK', text: 'SKIDS' },
  { value: 'TO', text: 'TOTES' },
  { value: 'TL', text: 'TRUCK' }
];
