//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated for use by Estes Express Lines Inc.
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.estes-express.com/ECM/imaging/queryImage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.estes.dto.ecm.image.query.request;
