//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated for use by Estes Express Lines Inc.
//


package com.estes.dto.ecm.image.delivery.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faxRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faxRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faxNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="faxCoverSheet" type="{http://www.estes-express.com/ECM/imaging/queryImage}faxCoverSheetDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faxRequest", propOrder = {
    "faxNumber",
    "faxCoverSheet"
})
public class FaxRequest {

    @XmlElement(required = true)
    protected String faxNumber;
    @XmlElement(required = true, nillable = true)
    protected FaxCoverSheetDetails faxCoverSheet;

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the faxCoverSheet property.
     * 
     * @return
     *     possible object is
     *     {@link FaxCoverSheetDetails }
     *     
     */
    public FaxCoverSheetDetails getFaxCoverSheet() {
        return faxCoverSheet;
    }

    /**
     * Sets the value of the faxCoverSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaxCoverSheetDetails }
     *     
     */
    public void setFaxCoverSheet(FaxCoverSheetDetails value) {
        this.faxCoverSheet = value;
    }

}
